### ISSUE TITLE
'Octanoyl-ACP' on PubChem

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#24] opened 2023-03-16 18:59 UTC
We get the information when we search this on the web page, but the API returns nothing, that's a BIG problem.

**Comment by Porthmeus** [comment] 2023-03-17 10:13
The problem is PubChem here. It distinguishes between compounds and substances. Compounds get a CID and are curated and completely defined. Substances are rather raw, and have missing information and are also duplicated from time to time. I used get_compound() to retrieve the pubchem entry, however get_substance exists. So we should probably add it as backup. For that specific case, there is no InChI in the entry, because it contains R groups. So we have to handle these R groups somehow...

**Comment by Porthmeus** [comment] 2023-05-23 07:38
OK the problem seems not to be urgent right now, will close it - we can reopen, if we encounter it again.

**Closed by Porthmeus** 2023-05-23 07:38 UTC
Labels: bug
